/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-30 08:39:44 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.sales;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insert_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/kim/pro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/kim/pro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1714616048719L));
    _jspx_dependants.put("jar:file:/D:/kim/pro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html charset=UTF8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("	<title>구매하기</title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/head.jsp", out, false);
      out.write("\r\n");
      out.write("	<style>\r\n");
      out.write("	#tb1 tr td, #tb1 tr th { line-height:48px; padding-top:0px; }\r\n");
      out.write("	#tb1 tr td div { line-height:48px; margin-top:10px; }\r\n");
      out.write("	#tb1 tr td div input { height:42px; margin-top:5px; }\r\n");
      out.write("	</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"full-wrap\">\r\n");
      out.write("    <!-- 헤더 부분 인클루드 -->\r\n");
      out.write("    <header id=\"hd\">\r\n");
      out.write("    	<div class=\"container\">\r\n");
      out.write("    		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/hd.jsp", out, false);
      out.write("\r\n");
      out.write("    	</div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <main id=\"contents\" class=\"contents\">\r\n");
      out.write("    	<div id=\"breadcrumb\" class=\"container breadcrumb-wrap clr-fix\" style=\"height:60px; line-height:60px;\">\r\n");
      out.write("	    	<nav class=\"breadcrumb\" aria-label=\"breadcrumbs\">\r\n");
      out.write("			  <ul>\r\n");
      out.write("			    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Home</a></li>\r\n");
      out.write("			    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/listAll.do\">상품</a></li>\r\n");
      out.write("			    <li class=\"is-active\"><a href=\"#\" aria-current=\"page\">구매</a></li>\r\n");
      out.write("			  </ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("    	</div>\r\n");
      out.write(" 	    <section class=\"page\" id=\"page1\">\r\n");
      out.write("    		<h2 class=\"page-title\">상품 구매</h2>\r\n");
      out.write("    		<div class=\"page-wrap\">\r\n");
      out.write("	    		<div class=\"clr-fix\">\r\n");
      out.write("	    			<br>\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sales/inSalesPro.do\" method=\"post\">\r\n");
      out.write("						<table class=\"table\" id=\"tb1\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th><h3>제품 정보</h3></th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<div class=\"item_fr\">\r\n");
      out.write("											<input type=\"hidden\" name=\"pno\" id=\"pno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" id=\"name\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" id=\"pname\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" name=\"id\" id=\"id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" id=\"email\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" id=\"custel\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.tel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" id=\"cusaddr\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.addr1 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" id=\"cusaddr2\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.addr2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" id=\"cuspostcode\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.postcode }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\r\n");
      out.write("											<input type=\"hidden\" name=\"gtid\" id=\"gtid\" />\r\n");
      out.write("											<h4>제품명 : ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</h4>\r\n");
      out.write("											<img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/upload/");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.img }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" alt=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pname }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" width=\"120\" />\r\n");
      out.write("											<br>\r\n");
      out.write("											<h4>제품 설명</h4>\r\n");
      out.write("											<p>");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.com }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("</p>\r\n");
      out.write("										</div>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th><h3>구매 정보</h3></th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<div class=\"item_fr\">\r\n");
      out.write("											<strong>단가 </strong> : \r\n");
      out.write("											<input type=\"number\" id=\"price\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.oprice }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"input\" style=\"display:inline-block; width:85%;\" readonly /><br>\r\n");
      out.write("											<strong>수량 </strong> : \r\n");
      out.write("											");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("											<br>\r\n");
      out.write("										</div>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("								");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<hr>\r\n");
      out.write("						<div class=\"buttons\">\r\n");
      out.write("						  <button type=\"submit\" class=\"button is-danger\" id=\"salesBtn\">구매</button>\r\n");
      out.write("						  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/product/detail.do?pno=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${product.pno }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" class=\"button is-primary\">해당 상품</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("		            <script>\r\n");
      out.write("	                function findAddr() {\r\n");
      out.write("	                    new daum.Postcode({\r\n");
      out.write("	                        oncomplete: function(data) {\r\n");
      out.write("	                            console.log(data);\r\n");
      out.write("	                            var roadAddr = data.roadAddress;\r\n");
      out.write("	                            var jibunAddr = data.jibunAddress;\r\n");
      out.write("	                            document.getElementById(\"postcode\").value = data.zonecode;\r\n");
      out.write("	                            if(roadAddr !== '') {\r\n");
      out.write("	                                document.getElementById(\"addr1\").value = roadAddr;\r\n");
      out.write("	                            } else if(jibunAddr !== ''){\r\n");
      out.write("	                                document.getElementById(\"addr1\").value = jibunAddr;\r\n");
      out.write("	                            }\r\n");
      out.write("	                            document.getElementById(\"addr2\").focus();\r\n");
      out.write("	                        }\r\n");
      out.write("	                    }).open();\r\n");
      out.write("	                }\r\n");
      out.write("	            	</script>\r\n");
      out.write("	            	<script src=\"https://t1.daumcdn.net/mapjsapi/bundle/postcode/prod/postcode.v2.js\"></script>\r\n");
      out.write("					\r\n");
      out.write("					<!-- 결제 API -->\r\n");
      out.write("					<script src=\"https://cdn.iamport.kr/js/iamport.payment-1.1.5.js\"></script>\r\n");
      out.write("					<script>\r\n");
      out.write("					$(document).ready(function(){\r\n");
      out.write("						\r\n");
      out.write("						$(\"#addr2\").focusout(function(){\r\n");
      out.write("							$(\"#addr\").val($(\"#addr1\").val()+\"   \"+$(\"#addr2\").val()+\"   \"+$(\"#postcode\").val());\r\n");
      out.write("						});\r\n");
      out.write("						\r\n");
      out.write("						$(\".change_item\").css(\"display\", \"none\");\r\n");
      out.write("						$(\".result_item\").css(\"display\", \"none\");\r\n");
      out.write("						$(\"#salesBtn\").css(\"display\", \"none\");\r\n");
      out.write("						\r\n");
      out.write("						$(\"#amount\").on(\"change\", function(){\r\n");
      out.write("							$(\"#tot\").val(parseInt($(\"#price\").val())*parseInt($(\"#amount\").val()));\r\n");
      out.write("							$(\".change_item\").css(\"display\", \"\");	\r\n");
      out.write("						});\r\n");
      out.write("						\r\n");
      out.write("						$(\"#amount\").on(\"keyup\", function(){\r\n");
      out.write("							$(\"#tot\").val(parseInt($(\"#price\").val())*parseInt($(\"#amount\").val()));\r\n");
      out.write("							$(\".change_item\").css(\"display\", \"\");	\r\n");
      out.write("						});\r\n");
      out.write("						\r\n");
      out.write("						$(\"#payBtn\").click(function(){\r\n");
      out.write("							var money = parseInt($(\"#tot\").val());\r\n");
      out.write("							var code = `");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${code}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("`;\r\n");
      out.write("							console.log(\"결제\");\r\n");
      out.write("					        IMP.init(code); // 가맹점 식별코드로 Iamport 초기화\r\n");
      out.write("					        IMP.request_pay({ // 결제 요청\r\n");
      out.write("					            pg: \"danal_tpay\",   // PG사 설정\r\n");
      out.write("					            pay_method: \"card\", // 결제 방법\r\n");
      out.write("					            merchant_uid: 'merchant_' + new Date().getTime(), // 주문 번호\r\n");
      out.write("					            name: $(\"#pname\").val(), // 상품 이름\r\n");
      out.write("					            amount: money, // 결제 가격\r\n");
      out.write("					            buyer_email: $(\"#email\").val(),\r\n");
      out.write("					            buyer_name: $(\"#name\").val(), // 구매자 이름 (buyer_ 부분은 꼭 작성하지 않아도된다. (선택사항))\r\n");
      out.write("					            buyer_tel: $(\"#custel\").val(), // 구매자 연락처\r\n");
      out.write("					            buyer_postcode: $(\"#cuspostcode\").val(), // 구매자 우편번호\r\n");
      out.write("					            buyer_addr: $(\"#cusaddr\").val() // 구매자 주소\r\n");
      out.write("					        }, function(rsp){\r\n");
      out.write("					        	\r\n");
      out.write("					        	var gt_id = \"12345678\";	//거래 승인 번호\r\n");
      out.write("					        	var card_name = \"삼성카드\";\r\n");
      out.write("					        	var card_number = \"1234567890123\";\r\n");
      out.write("					        	var pay_method = \"card\";\r\n");
      out.write("					        	var amount = money;\r\n");
      out.write("					        	\r\n");
      out.write("					        	if (rsp.success) {\r\n");
      out.write("					        		//결제 성공시 처리하는 구문들\r\n");
      out.write("						        	gt_id = rsp.apply_num;\r\n");
      out.write("						        	pay_method = rsp.pay_method;\r\n");
      out.write("						        	\r\n");
      out.write("						        	console.log('PG사 구분코드 : ' + rsp.pg_provider);\r\n");
      out.write("						        	console.log('고유ID : ' + rsp.imp_uid);\r\n");
      out.write("						        	console.log('상점 거래ID : ' + rsp.merchant_uid);\r\n");
      out.write("						        	console.log('결제 수단 : ' + rsp.pay_method);\r\n");
      out.write("						        	console.log('결제 금액 : ' + rsp.paid_amount);\r\n");
      out.write("						        	console.log('거래 매출전표 URL : ' + rsp.receipt_url);\r\n");
      out.write("						        	console.log('결제 통화 : '+rsp.currency);\r\n");
      out.write("						        	console.log('거래 승인번호 : ' + rsp.apply_num);\r\n");
      out.write("						        	\r\n");
      out.write("						        	if(rsp.pay_method=='card') { //카드인 경우\r\n");
      out.write("						        		console.log('신용 카드 이름 : ' + rsp.card_name);\r\n");
      out.write("						        		console.log('신용 카드 번호 : ' + rsp.card_number);\r\n");
      out.write("							        	card_name = rsp.card_name;\r\n");
      out.write("							        	card_number = rsp.card_number;\r\n");
      out.write("						        	}\r\n");
      out.write("						        	\r\n");
      out.write("						        	if(rsp.pay_method=='vbank') { //가상 계좌인 경우\r\n");
      out.write("							        	console.log('가상계좌 입금 계좌번호 : ' + rsp.vbank_num);\r\n");
      out.write("							        	console.log('가상계좌 입금 은행명 : ' + rsp.vbank_name);\r\n");
      out.write("							        	console.log('가상계좌 입금 예금주 : ' + rsp.vbank_holder);\r\n");
      out.write("						        	}\r\n");
      out.write("						        	\r\n");
      out.write("						        	if(rsp.pay_method=='trans') { //실시간 계좌이체인 경우\r\n");
      out.write("						        		//결제 응답 파라미터 참조\r\n");
      out.write("						        	}\r\n");
      out.write("						        	\r\n");
      out.write("						        	if(rsp.pay_method=='phone') { //휴대폰 소액결제인 경우\r\n");
      out.write("						        		//결제 응답 파라미터 참조	\r\n");
      out.write("						        	}						        	\r\n");
      out.write("\r\n");
      out.write("						        	if(rsp.pay_method=='samsung') { //삼성페이인 경우\r\n");
      out.write("						        		//결제 응답 파라미터 참조\r\n");
      out.write("						        	}\r\n");
      out.write("						        	\r\n");
      out.write("						        	if(rsp.pay_method=='kakaopay') { //카카오페이인 경우\r\n");
      out.write("						        		//결제 응답 파라미터 참조\r\n");
      out.write("						        	}\r\n");
      out.write("						        	\r\n");
      out.write("						        	if(rsp.pay_method=='naverpay') { //네이버페이인 경우\r\n");
      out.write("						        		//결제 응답 파라미터 참조\r\n");
      out.write("						        	}\r\n");
      out.write("						        	\r\n");
      out.write("						        	//여기에 나머지 코딩\r\n");
      out.write("						        	\r\n");
      out.write("						        	\r\n");
      out.write("					        	} else {\r\n");
      out.write("					        		//결제가 실패되었을 경우\r\n");
      out.write("					        		console.log('에러 코드 : '+rsp.error_code);\r\n");
      out.write("					        		console.log('에러 메시지 : '+rsp.error_msg);\r\n");
      out.write("					        	}\r\n");
      out.write("					        	\r\n");
      out.write("					        	console.log('결제 상태 : '+rsp.status);\r\n");
      out.write("					        	\r\n");
      out.write("					        	\r\n");
      out.write("					        	/* 아래 코드는 부분은 원래 if (rsp.success) { ... } 블록의 가장 아래에 넣어야 합니다.\r\n");
      out.write("					        		연습이므로 밖에 기술하였음\r\n");
      out.write("					        	*/\r\n");
      out.write("					        	\r\n");
      out.write("					        	pay_num = card_name+\" : \"+card_number;\r\n");
      out.write("					        	\r\n");
      out.write("					        	var msg = \"\";\r\n");
      out.write("					        	msg += \"결제수단 : \"+pay_method+\"<br>\";\r\n");
      out.write("					        	msg += \"결제번호 : \"+pay_num+\"<br>\";\r\n");
      out.write("					        	msg += \"결제금액 : \"+amount+\"<br>\";\r\n");
      out.write("					        	msg += \"거래 승인 번호 : \"+gt_id+\"<br>\";\r\n");
      out.write("					        	\r\n");
      out.write("					        	$(\"#paymethod\").val(pay_method);	\r\n");
      out.write("					        	$(\"#paynum\").val(pay_num);\r\n");
      out.write("					        	$(\"#gtid\").val(gt_id);\r\n");
      out.write("					        	\r\n");
      out.write("	                            $(\"#msg\").html(msg);\r\n");
      out.write("					            $(\".result_item\").css(\"display\", \"\");\r\n");
      out.write("	                            $(\"#salesBtn\").css(\"display\", \"inline-block\");\r\n");
      out.write("	                            \r\n");
      out.write("	                            \r\n");
      out.write("					        });\r\n");
      out.write("						});\r\n");
      out.write("					        \r\n");
      out.write("					});\r\n");
      out.write("					</script>\r\n");
      out.write("					<script>\r\n");
      out.write("					$(document).ready(function(){\r\n");
      out.write("					    // #ck2 checkbox가 클릭되었을 때\r\n");
      out.write("					    $(\"#ck2\").click(function(){\r\n");
      out.write("					        // 체크 상태를 확인하여 작업을 수행\r\n");
      out.write("					        if($(this).is(':checked')){\r\n");
      out.write("					            // 체크되었을 때 실행할 작업\r\n");
      out.write("					       		$(\"#rname\").val($(\"#name\").val());\r\n");
      out.write("					       		$(\"#addr1\").val($(\"#cusaddr\").val());\r\n");
      out.write("					       		$(\"#addr2\").val($(\"#cusaddr2\").val());\r\n");
      out.write("					       		$(\"#postcode\").val($(\"#cuspostcode\").val());\r\n");
      out.write("					       		$(\"#tel\").val($(\"#custel\").val());\r\n");
      out.write("					       		$(\"#isAddrBtn\").css(\"display\",\"none\");\r\n");
      out.write("					        } else {\r\n");
      out.write("					            // 체크가 해제되었을 때 실행할 작업\r\n");
      out.write("					       		$(\"#rname\").val(\"\");\r\n");
      out.write("					       		$(\"#addr1\").val(\"\");\r\n");
      out.write("					       		$(\"#addr2\").val(\"\");\r\n");
      out.write("					       		$(\"#postcode\").val(\"\");\r\n");
      out.write("					       		$(\"#tel\").val(\"\");\r\n");
      out.write("					       		$(\"#isAddrBtn\").css(\"display\",\"inline-block\");\r\n");
      out.write("					        }\r\n");
      out.write("					    });\r\n");
      out.write("					});\r\n");
      out.write("					</script>\r\n");
      out.write("				</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</section>\r\n");
      out.write("    </main>\r\n");
      out.write("    <!-- 푸터 부분 인클루드 -->\r\n");
      out.write("    <footer id=\"ft\">\r\n");
      out.write("    	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../include/ft.jsp", out, false);
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    	$(\"#tb1_length, #tb1_filter\").css(\"margin-bottom\", \"20px\");\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</div>    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/sales/insert.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path2");
      // /WEB-INF/views/sales/insert.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/sales/insert.jsp(5,0) '${pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/sales/insert.jsp(76,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.amount gt 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("												<input type=\"number\" name=\"amount\" id=\"amount\" min=\"1\" max=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.amount }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" step=\"1\" class=\"input\" style=\"display:inline-block; width:85%;\" required />\r\n");
          out.write("											");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/sales/insert.jsp(79,11) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${(inventory.amount eq 0) or (inventory.amount lt 1)}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("												<strong style=\"color:red\">품절</strong>\r\n");
          out.write("											");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/sales/insert.jsp(86,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.amount gt 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<tr class=\"change_item\">\r\n");
          out.write("									<th><h3>결제 정보</h3></th>\r\n");
          out.write("									<td>\r\n");
          out.write("										<div class=\"item_fr\">\r\n");
          out.write("											<strong>결제할 금액</strong> : \r\n");
          out.write("											<input type=\"number\" name=\"tot\" id=\"tot\" class=\"input\" style=\"display:inline-block; width:85%;\" required />											\r\n");
          out.write("										</div>\r\n");
          out.write("										<div class=\"item_fr\">\r\n");
          out.write("											<strong>결제 버튼을 누르세요</strong>\r\n");
          out.write("											<input type=\"hidden\" name=\"paymethod\" id=\"paymethod\" />\r\n");
          out.write("											<input type=\"hidden\" name=\"paynum\" id=\"paynum\" />\r\n");
          out.write("											<input type=\"hidden\" name=\"gtid\" id=\"gtid\" />\r\n");
          out.write("										</div>\r\n");
          out.write("										<button type=\"button\" id=\"payBtn\" class=\"button is-danger\">결제</button>\r\n");
          out.write("										<br>\r\n");
          out.write("										<div id=\"msg\">\r\n");
          out.write("											\r\n");
          out.write("											\r\n");
          out.write("										</div>\r\n");
          out.write("									</td>\r\n");
          out.write("								</tr>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f3_reused = false;
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/views/sales/insert.jsp(109,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${inventory.amount gt 0}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("								<tr class=\"result_item\">\r\n");
          out.write("									<th><h3>배송 정보</h3></th>\r\n");
          out.write("									<td>\r\n");
          out.write("										<div class=\"item_fr\">\r\n");
          out.write("											<strong>주문자</strong> :\r\n");
          out.write("											<strong>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${cus.name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</strong> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; \r\n");
          out.write("											<input type=\"checkbox\" id=\"ck2\">\r\n");
          out.write("											<label for=\"ck2\">주문자와 수신자가 동일합니다.</label>											\r\n");
          out.write("										</div>\r\n");
          out.write("										<div class=\"item_fr\">\r\n");
          out.write("											<strong>수신자</strong> :\r\n");
          out.write("											<input type=\"text\" name=\"rname\" id=\"rname\" class=\"input\" required /> 											\r\n");
          out.write("										</div>\r\n");
          out.write("										<div class=\"item_fr\">\r\n");
          out.write("											<h4>배송지</h4>\r\n");
          out.write("											<hr>\r\n");
          out.write("											<strong>기본 주소</strong> : <input type=\"text\" name=\"addr1\" id=\"addr1\" class=\"input\" style=\"display:inline-block; width:85%;\" required><br> \r\n");
          out.write("											<strong>상세 주소</strong> : <input type=\"text\" name=\"addr2\" id=\"addr2\" class=\"input\" style=\"display:inline-block; width:85%;\" required><br>\r\n");
          out.write("											<strong>상세 주소</strong> : <input type=\"text\" name=\"postcode\" id=\"postcode\" class=\"input\" style=\"display:inline-block; width:85%;\" required><br><br>\r\n");
          out.write("											<input type=\"button\" id=\"isAddrBtn\" class=\"button is-link\" value=\"주소 입력\" onclick=\"findAddr()\">\r\n");
          out.write("											<input type=\"hidden\" name=\"addr\" id=\"addr\" />											\r\n");
          out.write("										</div>\r\n");
          out.write("										<div class=\"item_fr\">\r\n");
          out.write("											<strong>연락처</strong> :\r\n");
          out.write("											<input type=\"tel\" name=\"tel\" id=\"tel\" class=\"input\" required><br> \r\n");
          out.write("										</div>\r\n");
          out.write("									</td>\r\n");
          out.write("								</tr>\r\n");
          out.write("								");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
      _jspx_th_c_005fif_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f3_reused);
    }
    return false;
  }
}
