/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.87
 * Generated at: 2024-05-29 10:25:39 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.admin.inventory;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class return_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/kim/pro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/kim/pro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1714616048719L));
    _jspx_dependants.put("jar:file:/D:/kim/pro03/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/pro03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html charset=UTF8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("	<title>상품 반출</title>\r\n");
      out.write("	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../include/head.jsp", out, false);
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"full-wrap\">\r\n");
      out.write("    <!-- 헤더 부분 인클루드 -->\r\n");
      out.write("    <header id=\"hd\">\r\n");
      out.write("    	<div class=\"container\">\r\n");
      out.write("    		");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../include/hd.jsp", out, false);
      out.write("\r\n");
      out.write("    	</div>\r\n");
      out.write("    </header>\r\n");
      out.write("    <main id=\"contents\" class=\"contents\">\r\n");
      out.write("    	<div id=\"breadcrumb\" class=\"container breadcrumb-wrap clr-fix\" style=\"height:60px; line-height:60px;\">\r\n");
      out.write("	    	<nav class=\"breadcrumb\" aria-label=\"breadcrumbs\">\r\n");
      out.write("			  <ul>\r\n");
      out.write("			    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">Home</a></li>\r\n");
      out.write("			    <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/listInventory.do\">재고</a></li>\r\n");
      out.write("			    <li class=\"is-active\"><a href=\"#\" aria-current=\"page\">반출</a></li>\r\n");
      out.write("			  </ul>\r\n");
      out.write("			</nav>\r\n");
      out.write("    	</div>\r\n");
      out.write(" 	    <section class=\"page\" id=\"page1\">\r\n");
      out.write("    		<h2 class=\"page-title\">상품 반출</h2>\r\n");
      out.write("    		<div class=\"page-wrap\">\r\n");
      out.write("	    		<div class=\"clr-fix\">\r\n");
      out.write("	    			<br>\r\n");
      out.write("					<form action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/productReturnPro.do\" method=\"post\">\r\n");
      out.write("						<table class=\"table\">\r\n");
      out.write("							<tbody>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th><label for=\"cate\">카테고리</label></th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<select id=\"cate\" class=\"select\">\r\n");
      out.write("											<option value=\"\">선택안함</option>\r\n");
      out.write("											<option value=\"note\">노트</option>\r\n");
      out.write("											<option value=\"fancy\">팬시</option>\r\n");
      out.write("											<option value=\"pen\">필기구</option>\r\n");
      out.write("											<option value=\"binder\">파일철/바인더</option>\r\n");
      out.write("											<option value=\"other\">집기류/기타</option>\r\n");
      out.write("										</select>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th><label for=\"pno\">상품명</label></th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<select name=\"pno\" id=\"pno\" class=\"select\">\r\n");
      out.write("											<option value=\"\">선택안함</option>\r\n");
      out.write("\r\n");
      out.write("										</select>\r\n");
      out.write("										<input type=\"hidden\" name=\"pname\" id=\"pname\" />\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th><label for=\"iprice\">입고가격</label></th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<input type=\"number\" name=\"iprice\" id=\"iprice\" min=\"0\" step=\"100\" class=\"input\" required>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th><label for=\"oprice\">출고가격</label></th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<input type=\"number\" name=\"oprice\" id=\"oprice\" min=\"0\" step=\"100\" class=\"input\" required>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th><label for=\"amount\">반출 수량</label></th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<input type=\"number\" name=\"amount\" id=\"amount\" min=\"0\" step=\"1\" class=\"input\" required>\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("								<tr>\r\n");
      out.write("									<th><label for=\"remark\">참고 사항</label></th>\r\n");
      out.write("									<td>\r\n");
      out.write("										<input type=\"text\" name=\"remark\" id=\"remark\" class=\"input\">\r\n");
      out.write("									</td>\r\n");
      out.write("								</tr>\r\n");
      out.write("							</tbody>\r\n");
      out.write("						</table>\r\n");
      out.write("						<hr>\r\n");
      out.write("						<div class=\"buttons\">\r\n");
      out.write("						  <button type=\"submit\" class=\"button is-danger\">상품 반출 처리</button>\r\n");
      out.write("						  <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/listInventory.do\" class=\"button is-primary\">상품 재고 목록</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</form>\r\n");
      out.write("					<script>\r\n");
      out.write("					$(document).ready(function(){\r\n");
      out.write("						$(\"#cate\").change(function(){\r\n");
      out.write("							var value = $(this).val();\r\n");
      out.write("							if(value!=\"\"){\r\n");
      out.write("								$.ajax({\r\n");
      out.write("			                        url:\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path2 }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/admin/categoryLoading.do\",	//아이디가 전송되어질 곳\r\n");
      out.write("			                        type:\"get\",		//전송방식\r\n");
      out.write("			                        data: { cate : value },\r\n");
      out.write("			                        dataType:\"json\",	//데이터 반환 방식\r\n");
      out.write("                                    success: function(result){\r\n");
      out.write("                                    	console.log(result);\r\n");
      out.write("                                        var $pno = $(\"#pno\");\r\n");
      out.write("                                        $pno.empty(); // 기존 옵션 비우기\r\n");
      out.write("                                        $pno.append(\"<option value=''>선택안함</option>\");\r\n");
      out.write("                                        if (result && result.length > 0) {\r\n");
      out.write("                                            $.each(result, function(index, item) {\r\n");
      out.write("                                                var option = $(\"<option></option>\").val(item.pno).text(item.pname);\r\n");
      out.write("                                                $pno.append(option);\r\n");
      out.write("                                            });\r\n");
      out.write("                                        } else {\r\n");
      out.write("                                            $pno.append('<option value=\"\">해당 카테고리에 상품이 없습니다</option>');\r\n");
      out.write("                                        }\r\n");
      out.write("                                    },\r\n");
      out.write("                                    error: function() {\r\n");
      out.write("                                        alert(\"상품 목록을 불러오는 중 오류가 발생했습니다.\");\r\n");
      out.write("                                    }\r\n");
      out.write("			                    });\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("						\r\n");
      out.write("						$(\"#pno\").change(function(){\r\n");
      out.write("							var value = $(this).text();\r\n");
      out.write("							$(\"#pname\").val(value);\r\n");
      out.write("						});\r\n");
      out.write("					});\r\n");
      out.write("					</script>\r\n");
      out.write("				</div>\r\n");
      out.write("    		</div>\r\n");
      out.write("    	</section>\r\n");
      out.write("    </main>\r\n");
      out.write("    <!-- 푸터 부분 인클루드 -->\r\n");
      out.write("    <footer id=\"ft\">\r\n");
      out.write("    	");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "../../include/ft.jsp", out, false);
      out.write("\r\n");
      out.write("    </footer>\r\n");
      out.write("    <script>\r\n");
      out.write("    $(document).ready(function(){\r\n");
      out.write("    	$(\"#tb1_length, #tb1_filter\").css(\"margin-bottom\", \"20px\");\r\n");
      out.write("    });\r\n");
      out.write("    </script>\r\n");
      out.write("</div>    \r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/admin/inventory/return.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path2");
      // /WEB-INF/views/admin/inventory/return.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/admin/inventory/return.jsp(5,0) '${pageContext.servletContext.contextPath }'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.servletContext.contextPath }",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }
}
